### ISSUE TITLE
add suporrt for declaring or running tests

### ISSUE THREAD

**Issue by divinusdracodominus** [ValeLang/Fountain#12]
tests are an important part of making sure code runs properly, and consistently. in order to facilitate seamless testing, supposing that fountain supports a tests feature, vale tests can easily be envoked.

How it'll work for now
1. flag to fountain such as --tests "stdlib.stringutils.tests" "stdlib.command.tests"

How it could be made better in the future:
```toml
[[features]]
name = "command"
// ...
[[tests]]
path = "stdlib/command/tests"
requires = "command"
```
